version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vs_chat_admin_app
    restart: unless-stopped
    working_dir: /dist
    ports:
      - "127.0.0.1:3001:3000"